apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "postgresql.fullname" .) }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}

