{{- $rootPasswordValue := (randAlpha 16) | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.secretAdmin" . }}
  labels:
  {{- include "keycloak.labels" $ | nindent 4 }}
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ .Values.AdminUser | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ $rootPasswordValue }}




